Right now, we will work with a simple dataset called iris dataset. 

In [116]:
# import the required datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
%matplotlib inline 
from sklearn.metrics import confusion_matrix
#the output of plotting functions is shown here itself by using %matplotlib inline

In [117]:
# pandas is a data manipulation library that we are using to import a csv as a dataframe
df = pd.read_csv('iris.csv')

In [118]:
# this gives you the top 5 elements in the dataframe or you can even mention the required number of elements you want as a parameter
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [119]:
# here we are separating the dependent and independent variables
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
print(X)
print(y)

[[ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5  1.6  0.6]
 [ 5.1  3.8

In [120]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [121]:
print('Number of samples in the dataset are {}'.format(X.shape[0]))
print('Number of attributes are {}'.format(X.shape[1]))

Number of samples in the dataset are 149
Number of attributes are 4


In [122]:
# we divide the data into training and testing data
# test_size = provide the fraction of data to be considered as test size 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) 

In [123]:
print('After train test split---')
print('Number of samples in training set are {}'.format(X_train.shape[0]))
print('Number of samples in testing set are {}'.format(X_test.shape[0]))

After train test split---
Number of samples in training set are 104
Number of samples in testing set are 45


# Data Preprocessing

In [124]:
# scaling - scaling is an important data preprocessing step that it done to bring all the values within a particular range
#StandardScalar scales each value such that the mean becomes 0 and standard deviation becomes 1
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Learning Step

In [125]:
#lets use KNN for classification
k_values = []
accuracy = []
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

0.97777777777777775

In [126]:
#confusion matrix helps us in knowing the true positives, negatives and false positives and negatives
cm = confusion_matrix(y_test, y_pred)
cm

array([[8, 5, 4],
       [6, 5, 3],
       [2, 9, 3]], dtype=int64)

# We can never always go with accuracy, there are other metrics like precision, recall, f1 score etc. 